// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7W_1R5ggntlKX6EFjPv9AUkX4YcraSGo',
    appId: '1:682984058655:web:91da0a908fa264aa9e0a2a',
    messagingSenderId: '682984058655',
    projectId: 'gimiauto-af32b',
    authDomain: 'gimiauto-af32b.firebaseapp.com',
    storageBucket: 'gimiauto-af32b.firebasestorage.app',
    measurementId: 'G-KLX44865RD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4Iziy_kM0zxIMdNr5s91K9HU9js8acrM',
    appId: '1:682984058655:android:72c1b113b99a900e9e0a2a',
    messagingSenderId: '682984058655',
    projectId: 'gimiauto-af32b',
    storageBucket: 'gimiauto-af32b.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHLSzJKU9_xUezPLtLE9IY6NPTz-BcUjQ',
    appId: '1:682984058655:ios:f497dcb611a0571a9e0a2a',
    messagingSenderId: '682984058655',
    projectId: 'gimiauto-af32b',
    storageBucket: 'gimiauto-af32b.firebasestorage.app',
    iosBundleId: 'com.example.autoMobileSoftware',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHLSzJKU9_xUezPLtLE9IY6NPTz-BcUjQ',
    appId: '1:682984058655:ios:f497dcb611a0571a9e0a2a',
    messagingSenderId: '682984058655',
    projectId: 'gimiauto-af32b',
    storageBucket: 'gimiauto-af32b.firebasestorage.app',
    iosBundleId: 'com.example.autoMobileSoftware',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3sI9yVAEnqxR20RXQg8lXSyHzdJgxPws',
    appId: '1:682984058655:web:4f656a49bca2872b9e0a2a',
    messagingSenderId: '682984058655',
    projectId: 'gimiauto-af32b',
    authDomain: 'gimiauto-af32b.firebaseapp.com',
    storageBucket: 'gimiauto-af32b.firebasestorage.app',
    measurementId: 'G-WP6Z33SCGM',
  );
}
